common_mode:
  - .minecraft/**
  - '@^[^/]+\.txt'
  # - 'test/*.jar'
once_mode: 
  - 'test/*'
  # - .minecraft/test
  # - '@\.minecraft/mods/[^/]+\.jar'
  # - '.minecraft/1.12.2-forge1.12.2-14.23.5.2855'
  # - \.minecraft/1.12.2-forge1.12.2-14.23.5.2855
  # - \\.minecraft/modes
